### ISSUE TITLE
Delete document

### ISSUE THREAD

**Issue by wgohier** [xtralifecloud/xtralife-api#2]
The index is not refresh when you use index.delete method.
So if you delete then you reload datas just after it can work or not  depending on how lucky/unlucky you are which is super annyoing.

The method misses a parameter "refresh:true" when executing ES query to force index refreshing.

My alternative method is :

```
const idToDelete = "5d779d606379399f325d217a";
const client = self.index.getClient();
const deleteDocument = async function(index, type, id ){
       return await client.delete({  index, type, id, refresh: true });
 }
deleteDocument ( "index", "type", idToDelete );
```

A fix would be (or add as parameter on call)

https://github.com/xtralifecloud/xtralife-api/blob/5a8aa702fb0db216318ed494ba456c040aa54c0f/src/lib/index.coffee#L108

```
 @elastic.delete
				index: domain.toLowerCase()
				type: indexName
				id: objectId
  				refresh : true
```

**Comment by chrisDeFouRire** [comment]
The best way to get the instant refresh is indeed to use the client directly. For performance reasons, we will not update the index API: read you writes guarantee isn't one you always need, and the index API isn't supposed to be transactionally coherent... Also `getClient()` gives you the flexibility when simplicity isn't good enough ;-)
